export App from './App/App';
export RequireLogin from './RequireLogin/RequireLogin';
export Home from './Home/Home';
export Sporta from './Sporta/Sporta';
export NotFound from './NotFound/NotFound';
export Register from './Register/Register';
// export Account from './Account/Account';
export League from './League/League';
export LeagueProfile from './LeagueProfile/LeagueProfile';
export Team from './Team/Team';
export TeamProfile from './TeamProfile/TeamProfile';
export Athlete from './Athlete/Athlete';
export UserDetails from './UserDetails/UserDetails';
export Explore from './Explore/Explore';