export App from './App/App';
export RequireLogin from './RequireLogin/RequireLogin';
export Home from './Home/Home';
export Sporta from './Sporta/Sporta';
export NotFound from './NotFound/NotFound';
export Register from './Register/Register';
// export Account from './Account/Account';
export League from './League/League';
export Team from './Team/Team';
export Athlete from './Athlete/Athlete';
export UserDetails from './UserDetails/UserDetails';
export Explore from './Explore/Explore';
export Manage from './Manage/Manage';
export Profile from './Profile/Profile';
export Contact from './Contact/Contact';
